### ISSUE TITLE
Updates to descriptions

### ISSUE THREAD

**Issue by barsk** [gagagu/Arduino_FFB_Yoke#3]
Hi looking at your awesome project and greatly impressed. Did you actually implement the FFB protocol forces yourself just by looking through the specs? Really impressive. I have been fiddling a bit with that as well, but I ended up using some other code that was on the net as a basis and then refined that.

The description and specs seem somewhat outdated though as the HW with version 2.0 is s bit different. Would it be possible for you to find some time to update them? I guess some of the 2.0 changes affect electronics and software?

I have a question about the motors, in the 2.0 version a 4:1 gear is used to reduce rpm and increase torque, however why no go a bit further with the gears to get a bit more torque? I guess you do not need that much rpm really? Or?

These motors with attached gears rate from 5 to 600 rpm and are attainable in the EU at reasonable prices. I'm just not sure which motor to choose? [https://www.plexishop.it/en/robotics-and-automation/motors-for-arduino/dc-motors.html](https://www.plexishop.it/en/robotics-and-automation/motors-for-arduino/dc-motors.html)

**Comment by gagagu** [comment]
Hi, the FFB Protocol is not created by me. It's based on the Prject called "Fino" (see in Description). This is not the right place to discuss your case and i would invite you to my Discord to discuss it further. See the discord link in the project description, too.

I am working on a Cessna 172 panel, this also includes the implementation of the version 2.0 yoke. By this i will also update the documentation and software.

The newest Version 2.0 is a new hardware design which use the same pcb but instead of using IR Sensors we decided to switch to rotary encoders. The center IR Sensors are also not needed. But some small Code changes are needed to use this version. The changes are very small and not yet uploaded but i can send it to you if you contact me on Discord.

greetings

**Comment by barsk** [comment]
Thanks! I will join the Discord server asap. See you there. I'll leave the Issue open for the moment though until the descriptions are updated. Could be a help to others too se you comments I think.

**Comment by 1766029053** [comment]
So happy to have you join this forum

**Comment by gagagu** [comment]
Thx
